import {
  BadgeCheck,
  Boxes,
  Building2,
  Landmark,
  MapPin,
  Users,
  Wallet,
} from "lucide-react";

export const workflowSteps = [
  "Import Type",
  "Upload & Validate",
  "Review & Map",
  "Finalize",
];

/** Assets skips Review & Map and goes straight to Finalize. */
export const assetsWorkflowSteps = [
  "Import Type",
  "Upload & Validate",
  "Finalize",
];

export const importTypes = [
  {
    id: "members",
    title: "Members",
    description:
      "Validate member profiles, contact data, and onboarding attributes before import.",
    icon: Users,
    uploadRoute: "/single-upload/members/upload",
    reviewRoute: "/single-upload/members/review",
    resultsRoute: "/single-upload/members/results",
    status: "active",
    version: "V1",
    validationRules: [
      "Required Fields",
      "Email Validation",
      "Phone Validation",
      "Birth Date",
      "Gender",
      "Country Code",
      "Lead Status",
    ],
    supportedFormats: ["CSV"],
    requiredFiles: ["Members dataset"],
  },
  {
    id: "memberships",
    title: "Memberships",
    description:
      "Prepare recurring relationships and account-level attendance data.",
    icon: BadgeCheck,
    uploadRoute: "/single-upload/memberships/upload",
    reviewRoute: "/single-upload/memberships/review",
    resultsRoute: "/single-upload/memberships/results",
    status: "upcoming",
    version: "V1.1",
    validationRules: ["Subscription status", "Account linkages"],
    supportedFormats: ["CSV"],
    requiredFiles: ["Membership roster"],
  },
  {
    id: "assets",
    title: "Assets",
    description:
      "Validate asset photo imports: required headers, primary studio filter, resource type, image URLs, and duplicate resource IDs.",
    icon: Boxes,
    uploadRoute: "/single-upload/assets/upload",
    reviewRoute: "/single-upload/assets/results",
    resultsRoute: "/single-upload/assets/results",
    status: "active",
    version: "V1",
    validationRules: [
      "Required Headers",
      "Primary Studio Filter",
      "Resource Type",
      "Image URL",
      "Duplicate Resource ID",
    ],
    supportedFormats: ["CSV"],
    requiredFiles: ["Assets dataset"],
  },
  {
    id: "transactions",
    title: "Transactions",
    description:
      "Validate financial records and reconcile critical import fields.",
    icon: Wallet,
    uploadRoute: "/single-upload/transactions/upload",
    reviewRoute: "/single-upload/transactions/review",
    resultsRoute: "/single-upload/transactions/results",
    status: "upcoming",
    version: "V1.2",
    validationRules: ["Amount checks", "Currency normalization"],
    supportedFormats: ["CSV"],
    requiredFiles: ["Ledger export"],
  },
  {
    id: "locations",
    title: "Locations",
    description:
      "Verify location and regional compliance data for rollout initiatives.",
    icon: MapPin,
    uploadRoute: "/single-upload/locations/upload",
    reviewRoute: "/single-upload/locations/review",
    resultsRoute: "/single-upload/locations/results",
    status: "upcoming",
    version: "V1.3",
    validationRules: ["Region mapping", "Postal code match"],
    supportedFormats: ["CSV"],
    requiredFiles: ["Location master"],
  },
  {
    id: "institutions",
    title: "Institutions",
    description: "Validate organizational hierarchy and relationship records.",
    icon: Building2,
    uploadRoute: "/single-upload/institutions/upload",
    reviewRoute: "/single-upload/institutions/review",
    resultsRoute: "/single-upload/institutions/results",
    status: "upcoming",
    version: "V1.4",
    validationRules: ["Hierarchy check", "Naming consistency"],
    supportedFormats: ["CSV"],
    requiredFiles: ["Institution roster"],
  },
  {
    id: "programs",
    title: "Programs",
    description:
      "Assess program- and service-level data for downstream activation.",
    icon: Landmark,
    uploadRoute: "/single-upload/programs/upload",
    reviewRoute: "/single-upload/programs/review",
    resultsRoute: "/single-upload/programs/results",
    status: "upcoming",
    version: "V1.5",
    validationRules: ["Program codes", "Service mapping"],
    supportedFormats: ["CSV"],
    requiredFiles: ["Program catalog"],
  },
];
